# Linear sequence
testl_input = config["inputfile"]
nnodes = config["nnodes"]

rule testlc:
    input: f"testlc-{str(nnodes)}.txt" # the file created by the final step

rule testlc_reduce:
    input:
        lambda wildcards: f"testlc-{str(int(wildcards.value) - 1)}.txt" if int(wildcards.value) >= 0 else testl_input
    output:
        "testlc-{value}.txt"
    script:
        "mock.py"


rule testlt:
    input: f"testlt-{str(nnodes)}.txt" # the file created by the final step

rule testlt_reduce:
    input:
        lambda wildcards: f"testlt-{str(int(wildcards.value) - 1)}.txt" if int(wildcards.value) >= 0 else testl_input
    output:
        "testlt-{value}.txt"
    script:
        "mock.R"
