name: briefing
version: 0.1.0
homepage: null
synopsis: "Get briefings on this and that"
description: null
category: null
license: MIT
author: null
maintainer: null
github: null
bug-reports: null
dependencies: []
# Files to include when installing with `morloc make --install`
include: ["briefing.py"]
