rule plot:
  input:
    "04-named-tree/tree.json"
  output:
    "tree.pdf"
  shell:
    # All morloc aruguments must be JSON files or JSON strings. To pass a string
    # literal, morloc needs to receive a quoted string (otherwise it would be
    # invalid JSON and would be interpreted as a file). But Bash removes one
    # level of quotation, so '"<value"' quoting is required.
    """
    ./nexus.py plotTree '"{output}"' {input}
    """


rule name_leaves:
  input:
    "03-classified-tree/tree.json"
  output:
    "04-named-tree/tree.json"
  shell:
    "./nexus.py setNames {input} > {output}"


rule classify:
  input:
    "02-unclassified-tree/tree.json",
  output:
    "03-classified-tree/tree.json"
  shell:
    "./nexus.py classify {input} > {output}"


rule make_tree:
  input:
    "01-retrieved-data/retrieved.json"
  output:
    "02-unclassified-tree/tree.json"
  shell:
    "./nexus.py makeTree {input} > {output}"


rule retrieve_data:
  input:
    "data/config.json"
  output:
    "01-retrieved-data/retrieved.json"
  shell:
    "./nexus.py retrieve {input} > {output}"
